package com.abahz.africa.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.abahz.africa.model.Customer
import com.abahz.africa.repository.CustomerRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

class CustomerViewModel(private val repository: CustomerRepository) : ViewModel() {

    private val _customers = MutableStateFlow<List<Customer>>(emptyList())
    val customers: StateFlow<List<Customer>> = _customers.asStateFlow()

    private val _loading = MutableStateFlow(false)
    val loading: StateFlow<Boolean> = _loading.asStateFlow()

    private val _error = MutableStateFlow<String?>(null)
    val error: StateFlow<String?> = _error.asStateFlow()

    fun loadCustomers() {
        viewModelScope.launch {
            _loading.value = true
            try {
                _customers.value = repository.getCustomers()
                _error.value = null
            } catch (e: Exception) {
                _error.value = e.message
            } finally {
                _loading.value = false
            }
        }
    }

    fun addCustomer(customer: Customer) {
        viewModelScope.launch {
            try {
                repository.insertCustomer(customer)
                loadCustomers()
            } catch (e: Exception) {
                _error.value = e.message
            }
        }
    }

    fun updateCustomer(customer: Customer) {
        viewModelScope.launch {
            try {
                repository.updateCustomer(customer)
                loadCustomers()
            } catch (e: Exception) {
                _error.value = e.message
            }
        }
    }

    fun deleteCustomer(customerId: String) {
        viewModelScope.launch {
            try {
                repository.deleteCustomer(customerId)
                loadCustomers()
            } catch (e: Exception) {
                _error.value = e.message
            }
        }
    }

    fun signInOrRegister(phone: String, password: String, onResult: (Customer?) -> Unit) {
        viewModelScope.launch {
            _loading.value = true
            try {
                val existingCustomer = repository.getCustomerByPhone(phone)
                if (existingCustomer != null) {
                    if (existingCustomer.password == password) {
                        onResult(existingCustomer)
                    } else {
                        _error.value = "Mot de passe incorrect"
                        onResult(null)
                    }
                } else {
                    // Register new
                    val newCustomer = Customer(
                        phone = phone,
                        password = password,
                        created = 0L // Timestamp logic removed for cross-platform compatibility
                    )
                    repository.insertCustomer(newCustomer)
                    // Fetch it back to get the ID if generated by DB
                    val registered = repository.getCustomerByPhone(phone)
                    onResult(registered ?: newCustomer)
                }
                _error.value = null
            } catch (e: Exception) {
                _error.value = e.message
                onResult(null)
            } finally {
                _loading.value = false
            }
        }
    }
}
